:PROPERTIES:
:ID:       E777E93C-2CC3-425C-8311-DA463C946369
:END:
#+title: Dreamer
#+date:<2026-05-06 Wed>

# https://notebooklm.google.com/notebook/9f87aae1-5a46-4a2b-b1e4-67ec7eaa8b87

1. [[id:86AED53A-E457-4246-A5F7-C927DCE65274][Dreamer v1]] - ICLR 2020 - Dream to Control: Learning Behaviors by Latent Imagination [[[pdf:@papers/Dreamer v1 - 1912.01603v3.pdf::1++0.00][pdf]]]
2. [[id:A5E0D24E-C1DB-4157-9E86-AFA2D78E5D7B][Dreamer v2]] - ICLR 2021 - Mastering Atari With Discrete World Models [[[pdf:@papers/Dreamer v2 - 2010.02193v4.pdf::1++0.00][pdf]]]
3. [[id:9FCF9CDA-0450-4F70-B2C5-D27CBB437C65][Dreamer v3]]
   - arXiv 2023 - Mastering Diverse Domains through World Models [[[pdf:@papers/Dreamer v3 - 2301.04104v2.pdf::1++0.00][pdf]]]
   - Nature 2023 - Mastering diverse control tasks through world models [[[pdf:@papers/Dreamer v3 - Mastering diverse control tasks through world models.pdf::1++0.00][pdf]]]
4. [[id:5D2A9680-5378-4DA3-8C95-4EC361798502][Dreamer v4]] - arXiv 2025 - Training Agents Inside of Scalable World Models [[[pdf:@papers/Dreamer v4 - 2509.24527v1.pdf::1++0.00][pdf]]]

* Dreamer v1

[[id:86AED53A-E457-4246-A5F7-C927DCE65274][Dreamer v1]] outperformed other methods in performance, sample
efficiency and computational budget in the DeepMind continuous control
problems. But it only work well in a few of the Atari environments.

* Dreamer v2

[[id:A5E0D24E-C1DB-4157-9E86-AFA2D78E5D7B][Dreamer v2]] performed better than other methods in Atari environments
by making some tweaks to Dreamer v1. Specifically, using REINFORCE as
policy update algorithm, using categorical latents instead of
continuous and using a KL balancing technique for dynamics model.

Tested on 55 Atari games with 200M steps.

* Dreamer v3

[[id:9FCF9CDA-0450-4F70-B2C5-D27CBB437C65][Dreamer v3]] is the first algorithm to collect diamonds in Minecraft
from scratch without human data or curricula. Moreover, it works with
a single hyperparameter configuration for a wide range of tasks
(Atari, ProcGen, DMLab, Minecraft, Atari100k, Proprio Control, Visual
Control, BSuite).

* Dreamer v4

[[id:5D2A9680-5378-4DA3-8C95-4EC361798502][Dreamer v4]] uses transformer architecture to learn highly accurate
world models for complex environments. And RL is also done completely
inside the learned world model. Can collect diamond on Minecraft being
completely trained on offline dataset.

The training is done completely offline. Thus has potential to be
applied to physical robots for which partially trained robots can't be
deployed and thus training completely in offline data is needed.


* Plan2Explore - ICML 2020

Objective is to do exploration of environment without any task
specific information. Then when given the task, be able to do the task
in zero shot or few shot. The world model learnt by other (like
Dreamer v2) doesn't generalize zero-shot to different tasks. But world
model learnt by [[id:D46A3C31-BAF2-40A1-9631-75EFADD49FBF][Plan2Explore]] does generalize.

* Mastering URLB from Pixels - ICML 2023

# [[pdf:@papers/Mastering Unsupervised RL Benchmark from Pixels - 2209.12016v2.pdf::1++0.00][Mastering Unsupervised RL Benchmark from Pixels - 2209.12016v2.pdf]]

URLB (Unsupervised RL Benchmark) is a benchmark for the kind of
problem statement that Plan2Explore presents. This paper beats
Plan2Explore.

1. Pre-training:

   URLB has a 2M step pre-training phase.

   Latent Bayesian Surprise (LBS) is used as intrinsic motivation
   reward. This rewards the agent for finding states that the world
   model struggles to predict.

2. Fine-Turning

   URLB gives 100k steps for fine-tuning on a specific task.

   The critic is always discarded while the actor is kept for dense
   reward problems only.

   Dyna-MPC is used to plan from thousands of imagined trajectories to
   select a action before taking real step in the environment.

In URLB they have 93.59% score.

In addition to URLB they show good performance on Real-World RL
benchmark (RWRL).

* Some papers

- Choreographer - ICLR 2023
  - https://arxiv.org/pdf/2211.13350
  - Table 1 shows that Choreographer beats Plan2Explore (P2E).
  - This paper doesn't compare with Mastering URLB from Pixels.
- Diversity is all you need (DIAYN) - ICLR 2019
  - https://arxiv.org/pdf/1802.06070
- Constrained Ensemble Exploration for Unsupervised Skill Discovery - ICML 2024
  - https://arxiv.org/pdf/2405.16030
- Balancing State Exploration and Skill Diversity in Unsupervised Skill Discovery
  - IEEE Transactions on Cybernetics 2025
  - https://arxiv.org/pdf/2309.17203
